version: '3'

services:
  dockerlized_db_dev:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=ivf-user
      - POSTGRES_PASSWORD=Nn%j9nKRM(N3RINSN32
      - POSTGRES_DB=ivf
  web_dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - dockerlized_db_dev
    env_file:
      - ./.env.dev

volumes:
  postgres_data: