version: '3'

services:
  webserver_prod:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - web_prod
    volumes:
      - ./src/static:/code/static
      - ./src/media:/code/media

  dockerlized_db_prod:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=ivf-user
      - POSTGRES_PASSWORD=Nn%$nJ|djmK+)4==33nm3kd&%%j9nKRM(N3RINSN32
      - POSTGRES_DB=ivf

  web_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: [sh, -c, "gunicorn ivf.wsgi:application --bind 0.0.0.0:8000"]
    volumes:
      - ./src:/code
      - ./src/static:/code/static
    expose:
      - 8000
    depends_on:
      - dockerlized_db_prod
    env_file:
      - ./.env.prod

volumes:
  postgres_data:
